### ISSUE TITLE
I'm using the web SDK package to integrate it in a NextJS project, but I'm getting "ReferenceError: self is not defined"

### ISSUE THREAD

**Issue by mohamedalkhawam** [adjust/web_sdk#54]
I'm facing this issue whenever I import your SDK  as the following

`import Adjust from "@adjustcom/adjust-web-sdk"`

Whenever I use this Import way, The UI  get blocked and and an error message with 

`"ReferenceError: self is not defined" appears."`

 Then, I imported the SDK as dynamic import as the following 

```
const Adjust = import("@adjustcom/adjust-web-sdk");

    async initializeAdjust() {
        if (!this.adjust) {
            this.adjust = await Adjust;
            this.adjust.initSdk(this.config);
        }
    }
```

In this case the SDK works and I can see logs from the SDK on the console.log and I'm able to track events, but I'm still getting the same error on NextJS server console

Here is the full error 

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
ReferenceError: self is not defined
    at Object.<anonymous> (/Users/mohamedkamelalkhawam/projects/startappz/tv1001/web/node_modules/@adjustcom/adjust-web-sdk/dist/adjust-latest.js:10:4)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.@adjustcom/adjust-web-sdk (/Users/mohamedkamelalkhawam/projects/startappz/tv1001/web/build/server/pages/_app.js:1244:18)
    at __webpack_require__ (/Users/mohamedkamelalkhawam/projects/startappz/tv1001/web/build/server/webpack-runtime.js:33:42)
    at Function.__webpack_require__.t (/Users/mohamedkamelalkhawam/projects/startappz/tv1001/web/build/server/webpack-runtime.js:139:38)
error - unhandledRejection: ReferenceError: self is not defined
    at Object.<anonymous> (/Users/mohamedkamelalkhawam/projects/startappz/tv1001/web/node_modules/@adjustcom/adjust-web-sdk/dist/adjust-latest.js:10:4)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.@adjustcom/adjust-web-sdk (/Users/mohamedkamelalkhawam/projects/startappz/tv1001/web/build/server/pages/_app.js:1244:18)
    at __webpack_require__ (/Users/mohamedkamelalkhawam/projects/startappz/tv1001/web/build/server/webpack-runtime.js:33:42)
    at Function.__webpack_require__.t (/Users/mohamedkamelalkhawam/projects/startappz/tv1001/web/build/server/webpack-runtime.js:139:38)
```

```
NextJS Version: 13.1.2
React Version: 18.2.0
Node Version: 16.20.0
```

**Comment by erayideall** [comment]
me too i faced this error. did you find any solution for this issue ?

**Comment by erayideall** [comment]
> > me too i faced this error. did you find any solution for this issue ?
> 
> @erayideall Yes I could be able to find a good work around and it's working.
> 
> so basically, what you need to do is
> 
> 1. initialize the Adjust SDK in a useEffect
> 
> ```
> useEffect(( )=>{
> if(typeof window !== "undefined){
> // the adjustSDKService is a class I implemented which  exports the instance of the class.
> // I triggered here the initializeAdjust method from my class
> adjustSDKService.initializeAdjust()
> }
> },[])
> ```
> 
> 2. use require in an if condition to import the SDK
> 
> ```
> // The initializeAdjust method from my class checks if the instance is exists it dooes nothing else it initialize the SDK
> initializeAdjust() {
>     if (!this.adjust) {
>       this.adjust = require("@adjustcom/adjust-web-sdk");
>       await this.adjust.initSdk(this.config);
>     }
>   }
> ```

thank you so much it's worked!
